name: win

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  packages: write

jobs:

  test:
    name: Generate Jobs
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Jobs
        run: |
          docker build . -f  3.11\windows\nanoserver-ltsc2022\Dockerfile -t ghcr.io/chizkiyahu/python/python:win
          docker push ghcr.io/chizkiyahu/python/python:win
          docker images